### ISSUE TITLE
is there a way to reformat or translate the .nitrox save of the world to singleplayer save?

### ISSUE THREAD

**Issue by Fisheiyy** [SubnauticaNitrox/Nitrox#1000]
is there anyway to like reformat or translate the .nitrox save of the world to whatever the singleplayer version reads? or make it read the .nitrox file because it would be nice if I can play the world on singleplayer you used to be able to use the same save from singleplayer to multiplayer or am i just high?

**Comment by Fisheiyy** [comment]
also #1000 WOO

**Comment by Coding-Hen** [comment]
No, currently there is no way to translate the between the two

**Comment by Fisheiyy** [comment]
were you able to?

**Comment by TheClockTwister** [comment]
> finished being built at like 95% when it was 100% when i logged out

This is a known issue. I am currently only working on that in all of my free time. Here is what you can do to minimize this bug until we fixed it: Once you build the bases first part, only build on top and in the positive x,y directions (just build in all directions, 2 will be buggy and 2 will work). If you only build in these 2 directions and upwards, you won't experience this "95% finished" bug anymore. Faces like hatches, reinforcements and windows however are still a bit buggy...

If this doesn't work for you you probably need to pull the latest commit, because this only applies to the current master position of cause :)

**Comment by Fisheiyy** [comment]
> > finished being built at like 95% when it was 100% when i logged out
> 
> This is a known issue. I am currently only working on that in all of my free time. Here is what you can do to minimize this bug until we fixed it: Once you build the bases first part, only build on top and in the positive x,y directions (just build in all directions, 2 will be buggy and 2 will work). If you only build in these 2 directions and upwards, you won't experience this "95% finished" bug anymore. Faces like hatches, reinforcements and windows however are still a bit buggy...
> 
> If this doesn't work for you you probably need to pull the latest commit, because this only applies to the current master position of cause :)

thanks that helps but im just relearning/rebuilding everything in a singleplayer world where i can use others mods for convience sake and the sake of my base is always 100% when i login and it doesnt redo the aurora drive core explosion every login :) fix that too if you can PLEASE
