### ISSUE TITLE
Power management undsynchronised after disconnection reconnection

### ISSUE THREAD

**Issue by AshenShugar59** [SubnauticaNitrox/Nitrox#1051]
Hello,

I am playing with 2 friends with you mod and we are catching some serious issue around structures.
Everytime we disconnect / reconnect, items are powered off, and we can't find a way to power on except destroy it and build it again.
The problem is that it is very specific to each user session.

Example :
- We are both on the server and build a fabricator, which works well
- One of us disconnect and reconnect, he will see the fabricator offline, as I will see it online and I can use it.
This happens systematically, not random.

It happens only on structure we build, not on the starting rescue cell.

Server version 1.2.1.0.

Thanks guys

**Comment by acidscorch** [comment]
This issue adresses two themes:
1. Fabricator and other objects after reconnect have no power or are not working: This happens because these objects need to be linked to the underlying Base-Object which gets broken on reconnect (to be correct in detail, in most cases it is already broken while playing and not correctly saved on server). Work on this is already in progress, but this is a very complex theme.
2. General base energy syncing is not implemented yet. A first solution at reconnecting will be, that all the base energy objects (solar, reactor) will be initialized with 50% powerstate. This will result in having different energystates for every player but will make the mod playable and give an anchor point for future energy sync implementation.

**Comment by Jannify** [comment]
Moved to https://github.com/SubnauticaNitrox/Nitrox/issues/1160
