### ISSUE TITLE
Habitats and tools don't sync between players

### ISSUE THREAD

**Issue by getsmor** [SubnauticaNitrox/Nitrox#1110]
Each player has to make their own hatch, their own tools, their own habitats and all inventory items can only be traded with storage's. If you try to drop and item and have your friend pick it up, it wont be visible for the receiving player, just an empty hand. Habitats show up as unfinished so you cant build onto them, hatches don't show up for other players and fabricators will show up as unpowered for all other players, even if they can see it.

**Comment by EinLuigi** [comment]
yes i have the same issue

**Comment by nickzema** [comment]
Hey! I am also having this issue. I didn't test enough to determine the issues with fabricators not working. but my wife and I are testing this and she sometimes can't see my hatch, sometimes she can't but can't use it, and when I put the hatch on top of a hall (rather than conventionally on the side as a doorway) she could enter, but not escape.

We will try seeing if it works if she makes her own hatch.

Thanks for this mod!
