### ISSUE TITLE
Sync radio messages and story ping points

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1113]
As shown in https://github.com/SubnauticaNitrox/Nitrox/issues/1078 we have a few problems with radio messages and story ping points.

- [ ] Save/Sync radio messages player wise
- [ ] Sync radio messages timers
- [ ] Save/Sync story ping points player wise

**Comment by acidscorch** [comment]
Hi @Jannify,

i don't think that this can be labeled as easy. 

Some of the StoryGoals are TimerScheduled. As the Server runs permanent or a player skips a play session while his friends keep playing on, this must be handled and maybe the player achieved goals updated on reconnect. 

Also the current implementation of Initialsyncing story goals has to be reworked, because currently they trigger all events related to achieving a goal, which for e.g. causes exploding aurora at every startup. 

From my point of view there are quite a few overrides that need to be done to subnautica methods to achieve this properly. If someone wants to code this, i could give assistent to where and what must be changed.

**Comment by acidscorch** [comment]
#1092

**Comment by dartasen** [comment]
New version of Nitrox is available, we shipped some fix for this. I'm closing it !
