### ISSUE TITLE
server connection issues

### ISSUE THREAD

**Issue by skeptology** [SubnauticaNitrox/Nitrox#1140]
sorry for the vague title, here is a list of issues ive been having 

- connection will be lost when host disconnects from remotely hosted server
-  occasionally the server will load players into separate instances of the game despite connecting to the same server  
- if the game crashes while in the server, upon trying to reconnect the server will not let you reconnect with the same username, the server will not show you as in the game either. while trying to kick me from the server the admin got a message that my username was not connected to the server 
-when another player places down a hatch, other players are unable to access the hatch, the hatch wont show up graphically, and has no hit box

**Comment by Jannify** [comment]
If the game crashes the server can't probably disconnect the player. The current solution to this is a restart of it.
The other issues sound like they are caused by your setup (PC/router/etc). I personally never heard of them. 
Pls try a clean install of nitrox and subnautica and check again if the problems persists. If so contact our support team on our discord server. :)
