### ISSUE TITLE
Seamoth randomly destroyed

### ISSUE THREAD

**Issue by paulsavary** [SubnauticaNitrox/Nitrox#1170]
Issued explosion of my Seamoth while casually docking in moonpool (not everytime). Same happend once while driving it near my friend (also in Seamoth), one of them exploded, without any collision...

**Comment by it-rec** [comment]
I had the same issue with my GF. She was so happy having the ressources for a moonpool, built it, docked with the seamoth and when the docking animation ended: The Seamoth just exploeded. We guess that it my be related to me beeing the host. So I came with my seamoth and try to dock too, just to evaluate. It turned out it didn't explode. I docked and undocked multiple times. Nothing bad happend. Unless I did some other things at the base and wanted to undock my docked seamoth....as it also exploded.

There is somthing terrible wrong as also for us there were no collisions and both seamoths had full life.

**Comment by CobaltWarrior9** [comment]
I have had this happen twice while trying to dock a seamoth into a cyclops in version 1.3.0.0

**Comment by Mikanosuke** [comment]
**Version:** 1.3.0.0

A Seamoth exploded immediately after leaving the Moonpool for me in multiplayer (2 players) so I guess the above issue is still present.
I was able to dock the Seamoth successfully into the Moonpool but seconds after leaving, as I was descending from it, it exploded for no apparent reason. This was the first (and only) time that I attempted using the Moonpool in multiplayer.

**Comment by EnzoTools** [comment]
Mine didn't explode, but it was stuck in a position and I had to use a booster :(

**Comment by dartasen** [comment]
Duplicate #1223
