### ISSUE TITLE
Main menu won't load

### ISSUE THREAD

**Issue by dillon435** [SubnauticaNitrox/Nitrox#1231]
Just updated to the latest release following the guide on the website, but now any time I try to launch the game with multiplayer enabled, the main menu doesn't load. It's just the Subnautica title and the water, not even music loads. I tried reinstalling it from scratch and that didn't work either. It worked with 1.2.2.0, so idk what could of changed.

**Comment by Traesh** [comment]
Same here

**Comment by Measurity** [comment]
Traesh is right. 1.3 changed how Nitrox is loaded so if you used Nitrox before it will have old files. These old files conflict with 1.3 Nitrox and cause an error which prevents the main menu from loading.

Since this is a known issue when upgrading Nitrox to 1.3 I'm gonna close this. Comment again if it doesn't work.
