### ISSUE TITLE
having problem connecting to friend and friend connecting to me

### ISSUE THREAD

**Issue by nik072** [SubnauticaNitrox/Nitrox#1270]
multiplayer client loaded...
unable to contact the remote server at ''******************".11000
what should i do

**Comment by Measurity** [comment]
This isn't related to Nitrox. Make sure you can connect to the server and that you have the correct IP. 

If you are hosting then you can use  the **loopback** (aka: localhost) IP: `127.0.0.1`.
If someone else is hosting then you need their (external) IP. The host should visit <https://whatismyipaddress.com/> and get the IPv4 then he should give it to whoever wants to join.

For above to work you need to do [Port Forwarding](https://portforward.com/). If you cannot do this because you don't own your network (school, business) then you need to use a VPN like Hamachi.

If you need help with this further then join our Discord. https://discord.gg/E8B4X9s
