### ISSUE TITLE
Crabsnake size

### ISSUE THREAD

**Issue by Tristinack** [SubnauticaNitrox/Nitrox#1379]
### Version
1.4.0.0
### Bug
Crabsnakes within the jellyshroom caves are between 3-5x bigger. They are all leviathan sized and it is terrifying, but you can also see them glitching through the floor and spazzing out.

### Expected
Crabsnakes are the regular size.

### Steps to reproduce
Launch the server, connect to the server, take a trip to jellyshroom caves, observe.

**Comment by gir489** [comment]
I can not replicate this issue. Please supply a world folder save archive near the area with expected beahviour.

**Comment by gir489** [comment]
Oh.... You must not be familiar with how NitroX works. It's basically spoofing the game to be at the crash point every time, then loading deltas between your save file. Because of this, the game thinks you're at the very end, or at least the end state of the game. Because of that, the crabsnakes are in their end-game state and the game is making them large. At least, that's what I can see in the code. Maybe the devs can comment on this issue? Maybe this is just another case of "we haven't explained this to the user yet because it's Alpha, we're still trying to get it to literally not shit its pants doing anything."

**Comment by dartasen** [comment]
Unable to replicate,  can you please provide some screenshots

**Comment by linuxchr** [comment]
I have also the same bug in v1.7.0.0

With the same steps to repruduce.

![theSIZE](https://user-images.githubusercontent.com/69758634/209918885-96f2543e-ea31-4dcc-90dc-ca7f198945fb.png)
