### ISSUE TITLE
Save file migration from version to version with Protobuf

### ISSUE THREAD

**Issue by romgerman** [SubnauticaNitrox/Nitrox#1411]
Hello. 
So I've been using version 1.4.0.0 and wanted to try latest changes. I've compiled mod myself with latest commit https://github.com/SubnauticaNitrox/Nitrox/commit/3963b2716192e29a6eb24539702abd6f6416a0de and it didn't load the save file from 1.4 because of version mismatch and protobuf format.

My question is:
Will you consider making protobuf save file upgrade system? And will it automatically update previous save file to the newest version?

**Comment by Measurity** [comment]
Yes: https://github.com/SubnauticaNitrox/Nitrox/pull/1370

Ideally we fully migrate to JSON which makes it easier to provide compatibility between versions since it doesn't need to be binary accurate to be able to load the save. Only downside with JSON is that the saves are quite large. We'll see where we'll go from here.

**Comment by romgerman** [comment]
Yes but currently this breaks old save files. They couldn't be loaded
