### ISSUE TITLE
I build a base, then when my friend joins, on his end, its flooded, the ENTIRE building is flooded. When I rejoin, the building is flooded and I have to keep REPAIRING when I rejoin the GAME!

### ISSUE THREAD

**Issue by damien1406** [SubnauticaNitrox/Nitrox#1421]
LATEST VERSION!
### Bug

I build a base, then when my friend joins, on his end, its flooded, the ENTIRE building is flooded. When I rejoin, the building is flooded and I have to keep REPAIRING when I rejoin the GAME!

### Expected

I was expecting for it to be gone when I fixed the CRACKS! BUT NO! IT WILL REPEAT AND REPEAT!

### Steps to reproduce
Join a game with your friend. Build something, then rejoin. Once you have rejoined, you'll notice that the building is flooded with water which is very unrealistic.

**Comment by sintre** [comment]
Had the same issue. 

To us it seemed as for instance energy was not shared by the players, meaning that if I made the energysources my friend had no energy. The same was the case with the scanner room, whoever turned it on got the correct locations. This was notable since material spawns also was separated, so if i looted a material and my friend turned on the scanner room for this material its location would show up anyway.

To me this indicates that there is a problem how the world is shared between the players.

In regards to basebuilding we also had issues with structure.  To us it seems like the game rebuilds the base each time a player is logged in and in this process the structure is below zero which causes flooding.

Hope this helps with further development

Best regards

**Comment by NinjaPedroX** [comment]
Energy and other general base bugs are known and mostly expected, since bases aren't fully synced yet. The flooding issue seems to come base integrity issues, where it's too low while loading the game as the result of base reinforcements not syncing / being fully built.

While building is in the works of being fixed and synced, I recommend that you try building much more reinforcements to your base (and try not to deconstruct things often) so that if any of them were to bug out and not fully build, the rest that haven't are still there to give your base positive integrity and prevent possible floods while loading into the game.

If it's not any of these bugs and isn't avoided by any of the workarounds I mentioned, it may just be a bugged state of your base that may be unfixable, in which the only fix that I know of would just be to restart your world and build back everything you had using creative mode / commands.

**Comment by Exso12Ecesis** [comment]
It's because you don't have enough reinforcement to your base so it's falling apart. The part where you don't see it initially is a sync bug though.

**Comment by TheClockTwister** [comment]
Any updates on this? @damien1406 can you confirm it was due to missing reinforcement plates?

Otherwise, related issues: #1030, #691
