### ISSUE TITLE
Clients should disconnect when returning to main menu.

### ISSUE THREAD

**Issue by djkool** [SubnauticaNitrox/Nitrox#145]
Clients should send a manual disconnect packet, or at least close the socket after exiting to the main menu.
I've notice the server not seeing the player disconnect until after they completely closes the game.

**Comment by MadMaxOfYore** [comment]
#159 fixes this issues. Users will now log out of the server and will no longer "linger" if they exit the game and leave the client running. 

(This is not available yet. It still needs to go through the review/merge process, but a fix is imminent.)

However, it should be noted that users should shut down their client prior to joining a new game. We still have some refactoring to do in order to remove some state caching that is occurring where it should not be. That is not likely to happen until after (or at least very near) an initial alpha build is released to the public - so we thank you for you patience and understanding while we work towards that end.

Does this resolve your issue? If it does, then we'd thank you to go ahead and close this ticket.

Thanks!
MadMax

**Comment by MadMaxOfYore** [comment]
Closing as I assume that the OP is not monitoring this thread.

**Comment by djkool** [comment]
I am monitoring. I was just waiting until the PR was accepted and the changes were in a master build where it could be tested before I closed.
