### ISSUE TITLE
I'm confused, where is the news for this and the statements of project completion?

### ISSUE THREAD

**Issue by Supersquirtle6** [SubnauticaNitrox/Nitrox#153]
This may be a dumb question, but I am confused as to when Nitrox is releasing and where the project is at in this stage of development. I really need help with this as I don't want to inject it and I want to download it when it is complete. So ,If you would be so kind, link me to a site that can tell me (not the Github or trello page.) or just tell me where the project is at in it's development?
Thank you.

SuperS.6

**Comment by MarijnS95** [comment]
There is currently no site, or anyone who can tell you what the status is or when a release will be made.

We are still stuck in a position with very few developers capable of dedicating enough time to this project. The only place I can link you to is the GitHub projects page, up there is a crude list of things we need to tackle before Nitrox is alpha-release worthy.

As such, we can't give any promises or guesstimates because we simply do not know when and how much people will be able to contribute *quality code*.
