### ISSUE TITLE
Items disappear or duplicate

### ISSUE THREAD

**Issue by Fraaahhh** [SubnauticaNitrox/Nitrox#1566]
### Version
1.5.0.1

### Bug
Items disappear or duplicate

### Expected
- Every time someone enters the server, all players' items are duplicated
- Sometimes the player's inventory is cleared

**Comment by Pietro2999** [comment]
It happened to me. I would say the duplication always happens when a inventory is opened/loaded when a player enters the server. But the items are ghost items because on server restart they disappear. If you drop those ghosts items an error is shown on the server console

**Comment by mcdelarosa** [comment]
It happened to me too. I think it happens when something changed in your inventary, but it happens not always.
Maybe when you enter in the world too(and you have already played)

**Comment by H4x0r-000** [comment]
I had the problem too. Sometimes even with storage containers. A friend of mine checked if the storage was deleted but for him it was completely normal so i rejoined the game an it seemed to work again.

**Comment by Flash1232** [comment]
Still happens on 1.6.0.0. Happens predominantly with multi-slot items.

**Comment by 20PercentRendered** [comment]
I solved this by making everyone join in order. The join order should always be the same as the order people joined in to the world the first time. 
For example:

1. Player 1
2. Player 2 
3. Player 3
4. Player 4

If everyone joins in this order, no issues occur. 
If someone leaves, that will cause no issues. However, they cannot rejoin as they "own" items from other people's inventories, which will cause duplication. 
Anyone who wasn't part of the first time the server was ran can join, but they should join last. 
So, the steps to mitigate:
1. Start server
2. Make sure everyone joins in order
3. No touching anything or opening your inventory before everyone is in and loaded fully (seeing the game world)
4. No rejoining without everyone leaving and then restarting the server. 

I think this could be because Player 1 will own some items of players that join after him, and so on. 
This could (maybe) be permanently fixed by making the server own and simulate everything, instead of splitting it onto players. This way, when someone joins, they get the most up-to-date gamestate directly from the server.

**Comment by sarayuuki** [comment]
I just passed this on the help channel and credited you.

Nice solve!

**Comment by Jannify** [comment]
Probably solved with new entity system
