### ISSUE TITLE
Ghost/blueprint base buildings glitching out

### ISSUE THREAD

**Issue by Doubs115** [SubnauticaNitrox/Nitrox#1637]
### Version
Alpha
1.5.0.1

### Bug
When reloading into a server some buildings seem to not go away when deconstructed prior to leaving for the day and some unbuilt blueprints are in random spots according to the layout of the base, but because they are still attached I cannot deconstruct some buildings and I can't get rid of the blueprint/ghost buildings. 

### Expected
blueprints should stay where placed, deconstructed buildings shouldn't rise from the dead, lastly canceled ghost constructions shouldn't forever haunt your base.

### Steps to reproduce
One way to produce this bug it seems that if more than 1 person is constructing or deconstructing a building at a time then reloading the server, also glitch building multiple instances inside themselves like an "I compartment" and a "vertical connector" in the same location with 1 or both of them disappearing until a reload.

### Other details:
I don't know what 100% why this happens, feels like something to do with save states or idk. I think it's also possibly related to how vehicle upgrades are disappearing and same goes for batteries/cells disappearing in there chargers.

<!-- Find your player.log located at `%appdata%\..\LocalLow\Unknown Worlds\Subnautica` e.g. C:\Users\Octocat\AppData\LocalLow\Unknown Worlds\Subnautica --
> 
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/7439160/Player.log)

**Comment by Damouchka** [comment]
J'ai toujours eu ce problème dans toutes mes parties multi et ce depuis le début du mod Nitrox...
C'est tellement frustrant qu'à chaque mise à jour je tente pour voir si le problème persiste et désinstalle directement en espèrent que ça soit résolu sur la prochaine mise à jour.
Pourquoi n'y a t'il pas de solution pour ces plan fantôme rouge qui persiste ????

**Comment by H4x0r-000** [comment]
Me and a friend had a similar issue. First all was working perfectly, but since we tried to build a bioreactor in a multipurpose room everything started to break. The first problem we had was, that if my friend (or the other way around) build the reactor it was syncing until it hit 94% then he could finish it normaly but for me it stayed unfinished. Deconstructing wasnt even synced at all. We restarted the server but the issue stayed the same. After deconstructing the whole room we had the same issue described above where there was a ghosty reactor floating next to the base. But it wasnt all, since then the whole base was kinda of. As me moved on building, our integrity was too low so the base got holes, the problem with that was, that it was only working for my friend and not for me. Also other buildings werent syncing anymore and ladders disapearing after save and server restart. Overall realy frustrating
