### ISSUE TITLE
Release Nitrox_1.7.1.0.zip flagged as Malware.

### ISSUE THREAD

**Issue by UANightfire** [SubnauticaNitrox/Nitrox#1969]
### Describe the issue

 Nitrox_1.7.1.0.zip and specifically NitroxLauncher.exe have been flagged as malware.
[https://www.virustotal.com/gui/file/92f4be23fd098350031cbe2f661f90c7377d691eec91808636d415b9741b029a](url)
![image](https://user-images.githubusercontent.com/74957496/211572280-b9b6e6a2-55c4-484f-858a-b3b6299cd6ec.png)

**Comment by Measurity** [comment]
Both of those are flags for "it *looks* suspicious" by Anti Virus vendors[^1]. We submit releases to the vendors for scanning, but not all of them update their scanners to approve Nitrox.

## The reason(s) why AVs flag Nitrox
 - **It modifies the game code**: Changing code of another process is something viruses like to do too.
 - **It can add firewall rule exceptions as admin**: However it needs your consent to work. Still, some Anti Virus don't like this code since this is normally done via a setup.exe.
 - **We don't have an [EV certificate](https://en.wikipedia.org/wiki/Extended_Validation_Certificate)**: This would make us trusted by Anti Virus vendors. Unfortunately, an EV certificate requires an expensive subscription.

If you don't trust the Nitrox release we provide, you can build Nitrox yourself by going to the [tags page](https://github.com/SubnauticaNitrox/Nitrox/tags) to download the source. Then, run the CLI commands as given on [our docs](https://subnauticanitrox.github.io/Documentation/docs/development/getting-started#cli-setup).

## Help us report Nitrox as a false positive
If you own a virus scanner that reports Nitrox, then we'd appreciate it if you submit Nitrox as a false positive. You can do so at your anti virus vendor's file submit page:
 - [Windows Security](https://www.microsoft.com/en-us/wdsi/filesubmission)
 - [Kaspersky](https://support.kaspersky.com/common/error/other/1870)
 - [AVG](https://www.avg.com/en-us/false-positive-file-form#pc)
 - [Avast](https://www.avast.com/submit-a-sample#pc)
 
> [!TIP]
> You can find the submit page via Google: 
> ```
> your_anti_virus_vendor report false positive
> ```

[^1]: generic threat documentation: https://threats.kaspersky.com/en/threat/DangerousObject.Multi.Generic/
