### ISSUE TITLE
Dead mod?

### ISSUE THREAD

**Issue by Superscifi** [SubnauticaNitrox/Nitrox#199]
Seems like this mod died. :(

**Comment by ivalldg** [comment]
I hope not

**Comment by Superscifi** [comment]
Unforntanetly I think it is. RIP our dream

**Comment by ivalldg** [comment]
Its still downloadable it is just hard and buggy.

**Comment by Superscifi** [comment]
I mean, i guess that's true
But i mean come on they were so close plz at least make an easier install

**Comment by ivalldg** [comment]
Its still happening just slow they dont make money off this. I wanted to start raising money to pay them to continue it

**Comment by nesrak1** [comment]
For me, I've been gone for a while and it's my spring break this week. I am still working on this project and I'm sure the others are too.

**Comment by Superscifi** [comment]
Oh ok thanks for the update

**Comment by ivalldg** [comment]
Thank you nesrak. You people working on this are awesome

**Comment by Superscifi** [comment]
Amen to that

**Comment by Jannify** [comment]
![grafik](https://user-images.githubusercontent.com/23176718/37671177-71042994-2c6b-11e8-820a-b4052a2d0b53.png)
8 days = dead?

**Comment by Superscifi** [comment]
Sorry boy I havent seen that

**Comment by MadMaxOfYore** [comment]
Nah - we're still cracking at it. I had to take a little time away for family on account of spring break. Additionally, UWE released an update that broke us in some pretty silly ways recently. I just have not had the heart to rip back into those areas because they are really, really tricky.

We'll get back into the swing of things in the next week or two. Stay tuned!
