### ISSUE TITLE
Unable to build main base pieces, shows up green but will not build. Only seems to affect multipurpose/ compartments and similar pieces.

### ISSUE THREAD

**Issue by DrKOmN** [SubnauticaNitrox/Nitrox#2037]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Main base pieces will not build with habitat builder. Shows up green but will not build, all resources in inventory, no clipping and no mods. Using Nucleus and Nitrox. 
Did have a look online at pktentially being a binding issue however cannot confirm and fixes afforded by the authors of the reddit posts did not work for me.

**Comment by NinjaPedroX** [comment]
What version of Nitrox are you using?

**Comment by DrKOmN** [comment]
Hi Ninja,

Away from PC atm but from what I gather its "a modified 1.8.0.0 version" which is what the Nucleus Coop gets automatically when you download the handler. 

When I get back to my PC I can check the stated version in the game.

**Comment by DrKOmN** [comment]
Thanks TheLxkas, appreciate the confirmation.

I'll go and see if I can get Nucleus end to look into it.

**Comment by Measurity** [comment]
The code on master isn't finished for release yet due to Living Large making significant code changes that we need to adapt. That's why we recommend playing on legacy branch of Subnautica with [latest Nitrox release](https://github.com/SubnauticaNitrox/Nitrox/releases/latest) since it will have some base building functionality (although still buggy, it's better than latest code on master branch).

Closing as we're aware of incomplete base sync. With the way bases in Subnautica work, any issue in one base piece can cause desync for the entire base but making 100 issues for every base feature is unmanageable at this time. Work is on-going in pull request: #1952

**Comment by DrKOmN** [comment]
Thank you Measurity that clears things up appreciate it.
