### ISSUE TITLE
Sync the spawn command

### ISSUE THREAD

**Issue by tornac1234** [SubnauticaNitrox/Nitrox#2084]
**On master**
Currently, the ``spawn`` (Subnautica's) command only spawns things on the local player. It is an easy source for desyncs as long as one of the players decide to use this command.

**Comment by dartasen** [comment]
Note: Something went wrong with [https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_Patch.cs](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_Patch.cs) since 2.0, might be a good investigation point to begin with
