### ISSUE TITLE
Router Shutoff when server start

### ISSUE THREAD

**Issue by DragonScholar77** [SubnauticaNitrox/Nitrox#2125]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

I have a friend who just got nitrox and opened it as an admin. Soon after he clicked "start server" his router completely shut down.

### Describe the steps you took to encounter the bug.

I really have no clue how it happened. He was screen sharing on discord but when he clicked the button to start the server his stream froze, then he texted me on mobile saying his router shut off.

**Comment by Measurity** [comment]
When you start the server, it attempts to port forward 11000 UDP on your local router. Some routers don't support port forwarding. Some routers crash because they didn't implement UPnP correctly. 

What you can do is open the server.cfg file and disable the port forwarding feature.

This means you have to port forward yourself by logging in to your router. Alternatively, you can use a VPN to play like Hamachi or ZeroTier.
