### ISSUE TITLE
Player positions arn't properly synced

### ISSUE THREAD

**Issue by CtrlAltDavid01** [SubnauticaNitrox/Nitrox#232]
![desync](https://user-images.githubusercontent.com/18748408/42125177-c7ca0db0-7c71-11e8-8713-bb58f29a55c1.PNG)

I tested it in water too, but it's the same.
I apologize if it has already been reported.

**Comment by quimnuss** [comment]
I believe everybody is aware of this shift. The position is in sync, but there's the vertical shift to fix.

**Comment by quimnuss** [comment]
I've looked a little bit into this. Translating the model at creation does not fix it because the remote model shifts after certain actions: Touching sea floor, entering a room.

`RemotePlayer.cs:39             PlayerModel.transform.Translate(0, -1, 0);`

Maybe somebody else can give it a try with a different approach.

**Comment by MarijnS95** [comment]
@quimnuss As you correctly mentioned, we are already very aware of this minor issue, and know what's causing it; the way we currently deal with incoming positional packets together with gravity and smoothing. I had a fix for this a while ago but have unfortunately not had the time or motivation to clean it up and push it yet.

Based on the picture your solution will make one of the two much worse ;)

**Comment by quimnuss** [comment]
I'm not the OP. In my experience, the shift has always been +1 on spawn inside the lifepod. Hence the 0, -1, 0 ;)
