### ISSUE TITLE
Bioreactor Bugged

### ISSUE THREAD

**Issue by Vanghelion** [SubnauticaNitrox/Nitrox#239]
We've just tried to build a bioreactor and it is not in sync/its bugged.
Sometimes when i create it my friend cant see it, sometimes he can see it but cannot interact with it.

**Comment by quimnuss** [comment]
Bioreactors fail because the client throws the following exception:
`ThrottledBuilderSystem.InvalidOperationException: Nullable object must have a value.`
when client's `ConstructableBase` calls `BaseGhost component; component.Finish()`

The method `BaseGhost.Finish` is not entered, but since it is virtual, I figured it could also be overriden.

I've then also googled the exception, and I suspect the culprit is `BaseAddModuleGhost.anchoredFace`, which is nullable and might cause the exception when calling the `Finish()` method whilst this member being null.

**Comment by quimnuss** [comment]
Confirmed that the `BaseGhost` throwing the exception is of `BaseAddModuleGhost` type.

I also think that the problem is that the anchoredFace has the tag `[NonSerialized]` which probably means it isn't saved by UWE and it's just a matter of discovering how is it restored by them to replicate.

**Comment by quimnuss** [comment]
Confirmed that NuclearReactor suffers of the same problem.

Moreover, it all boils down to the MultiplayerBuilder.Update(). The update ultimatelly calls UpdatePlacement overriden by BaseAddModuleGhost who should be setting the anchoredFace.

However, it fails because Player.main has currentSub set to null. This causes UpdatePlacement to call SetupInvalid() and returns false to this UpdatePlacement in BaseAddModuleGhost:52

currentSub is of type SubRoot, which might be related to the context where the player is: in a Base or in the water... but I am not sure at all. Anyhow, the whole bioreactor/nuclearreactor comes from there.

**Comment by quimnuss** [comment]
I've been told there's a branch refactoring the whole building synchronization which might make this issue obsolete.
