### ISSUE TITLE
Still problem

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#354]
I have installed new files for NitroxServer but still nothing spawns

---
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData / Build18 is \ SNUnmanagedData \ Build18
[Nitrox] D: Loaded 0 entity-spawn-points for batch 12,16.8
[Nitrox] D: Batch 13,16.8 not parsed yet; parsing ...
---

**Comment by Sajgoniarz** [comment]
I debugged it, and path is correct, but in my case file is missing. Server tries to load ex. "D:\\gry\\subnautica\\SNUnmanagedData/Build18\\batch-cells-12-19-12-loot-slots.bin", but last file from batch 12,X,X is 12,18,22 and then 13,8,9. Server is trying to load data for visible cells, but there are no data for it, so i assume that error should not show.

**Comment by xkaczors** [comment]
I do not quite understand what's going on, did you fix the fault with the fish?

**Comment by xl3lackout** [comment]
> I do not quite understand what's going on, did you fix the fault with the fish?

he didnt. He's saying its trying to load files that arent there

**Comment by xl3lackout** [comment]
> I debugged it, and path is correct, but in my case file is missing. Server tries to load ex. "D:\gry\subnautica\SNUnmanagedData/Build18\batch-cells-12-19-12-loot-slots.bin", but last file from batch 12,X,X is 12,18,22 and then 13,8,9. Server is trying to load data for visible cells, but there are no data for it, so i assume that error should not show, but still for other cells i constantly get "Loaded 0 entity-spawn-points for batch X,Y,Z"

In the batchcellsparser.cs file it displays that whenever the file doesnt exist. Except its supposed to say the FILE that doesnt exist, it keeps saying the entire folder doesnt exist. Also i think those conflicting / and \ might be a problem. And ive tried editing the code so that it doesnt display the error, and it still does. Then i completely removed the entire file, and it still ran fine. I have no clue whats going on there
