### ISSUE TITLE
[Audio] Play audio effects

### ISSUE THREAD

**Issue by MarijnS95** [SubnauticaNitrox/Nitrox#37]
Currently behavior and usually animations are synced for actions, but sound is left out. Since sound is positional, this gives a much more immersive experience than if the other players are virtually silent.

#### TODO:
- Go over all the synced actions, and implement sounds on the receiver side if they play a sound on the sending side.
- Light toggles.
- Vehicle enters/exists.
- Base building and interaction.
- Swimming/walking.
- Tool usage.

**Comment by Jannify** [comment]
The problem is that some sounds are 2D and some 3D. 
So (for example) the Cyclops horn is 3D and easy to sync (see [the processor](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxClient/Communication/Packets/Processors/CyclopsActivateHornProcessor.cs) for reference).
On the other side are, for example most of the exosuit sound 2D.

Subnautica uses [FMOD](https://www.fmod.com/) which saves the sounds as an event, which is multiple sounds layered over each other modifiable with parameters. As a result, converting them from 2D to 3D would be a very hacky way or impossible.

As a solution we have to implement a manager which sets the volume of 2D sounds relatively to the distance of the player when fired.

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/pull/1291
