### ISSUE TITLE
What IP?

### ISSUE THREAD

**Issue by MasterPizza** [SubnauticaNitrox/Nitrox#398]
The local IP works and everything is smooth. I’m just unsure about what IP I should use to have friends join me. Thanks!

**Comment by Sajgoniarz** [comment]
But the first thing is you must have Public IP, what is really rare. Then whatsmyip will show you just NAT address

**Comment by crankineer** [comment]
Umm, no. Everyone has a public IP, it's not like a rarity or something given to only a few people.

**Comment by Sajgoniarz** [comment]
We talk about different things. Everyone have Public IP? Yes. Everyone has UNIQUE Public IP? No. That's what NAT serves for. That's why every device at my school had same Public IP, and that's why my neighbour from 4th floor of flat in front of mine have same Public IP as me, because of same ISP, and we could play Warcraft witch private (given by isp) ips.

**Comment by Sajgoniarz** [comment]
"we all have access to our public IP" - I didn't say, that we don't have. I said that not everyone have it's own and unique and I typed examples.

**Comment by Measurity** [comment]
Server now prints IP that you need to give to other people. See https://github.com/SubnauticaNitrox/Nitrox/pull/401
