### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by WerewolfsX** [SubnauticaNitrox/Nitrox#459]
As stated on a previous post  discord link has expired. I have sent a message to sunrunner37 to his profile at nexus mods. If he could get in touch with me about fan server i created for the mod that would be great.

**Comment by EsEsmuHooligan** [comment]
In my experience with the Nitrox mod that adds a multiplayer choice to the game there were a few things i would like to notify the creator as something for them to hopefully fix. the first is that the acid mushrooms which are  very common item to find were not spawning or appearing whenever me and my friend were looking for them. Without this item it is essentially impossible to complete and, or progress in the game. The second is it is very laggy. I do understand it is a big game but it should run fairly smoothly on a decent computer and i have also talked to some others that said they had this mod and were using a private internet connection with insanely good gaming only PC's and they were still lagging. The final problem that I wanted to address is that it seems to be merely impossible to find a link to the discord where the players were able to join and ask why certain things may not be working on these servers. I thought ( like many others ) that it would be a good idea to find a way to display a discord link that is easy to find. That is all I had wished to address and I hope that these things will be fixed in the future. Otherwise, great work on this mod I think it is a great addition to the game and good luck.

**Comment by Coding-Hen** [comment]
I think that this can now be closed as the link has been updated as per [Commit](https://github.com/SubnauticaNitrox/Nitrox/commit/d5d373aaf10c05e64d0638a977599ebed3dcd9b8#diff-04c6e90faac2675aa89e2176d2eec7d8)
