### ISSUE TITLE
Aurora Keypad/Door are double

### ISSUE THREAD

**Issue by Aocxiez** [SubnauticaNitrox/Nitrox#503]
Inside the Aurora ship doors and key pads are doubled.

**Comment by zheka-100500** [comment]
True such a bug is present it also works with data boxes, cubes, PDA and some other things.

**Comment by Agent77326** [comment]
In single-player (on server running) the chest pda etc. are only single. But when a friend joins, there are two chest (overlay each other), pda are still only single.

**Comment by sparhawk765** [comment]
I'm having the same but on a new server with only me logged in. All chests, PDA's and other artificial objects seems dubplicated. I'm guessing this also applied to buildings and machines which might be a reason scanning them is sometimes hard as it seem to reset the progress when you switch between the two instances of the object (due to bobbing probably).
