### ISSUE TITLE
A few problems I found that after searching the few 100 opened issues and closed

### ISSUE THREAD

**Issue by VanixHD** [SubnauticaNitrox/Nitrox#528]
1. Both players do not share the same view so for example I would see 4 table corals, the other does not see anything at the same spot.
2.The sea refreshes every so often we get out of the sea for some air, Its really hard to find stuff because I know where it is but because of this problem I have to look everywhere.
3.Sometimes the days are skipped in the tabs so I suddenly day 67 at day 18 then day 137
4. The story line doesn't share meaning I fix the ship but the other player will have to fix it  again and on radio cordinates it would not appear on the other player's screen.
5.This might be linked to the saving problem but you loose all the cordinates after you leave I tested it with saving first and no saving and both seem to not work

**Comment by VanixHD** [comment]
And a few more
3.Sometimes the days are skipped in the tabs so I suddenly day 67 at day 18 then day 137
4. The story line doesnt share meaning I fix the ship but the other player will have to fix it  again.
5.This might be linked to the saving problem but you loose all the cordinates after you leave I tested it with saving first and no saving and both seem to not work/

**Comment by toguno** [comment]
-Also equipped items also dissapear
-Repairing things on one persons end does not repair them on anyone elses end
-base items cannot be deconstructed
-scanner rooms are semi bugged, map and such appears outside the room to the right, in our case its in the water
-bioreactors dissapear
-seamoths can occasionally explode for no apparent reason (both times in the pod area)
-when the server restarts it seems the story line does too. The aurora reexplodes without warning (we were inside the aurora once when it did), and the leak reappared.
-anything built that floats such as a mobile vehicle bay dissapears upon relog or restart
-extinguished fire does not sync
-the little tiny leach things in the aurora are passive due to this mod
-the fish that hypnotize you (forgot the name) do not spawn
-some of the doors in aurora are bugged and unable to be repaired, we had to use the “unlockdoors” command to get through
- SPOILERS — both my friend and i got the bacterial infection on our skin at the same time, but that was reset upon server reboot.
- the server crashes about once per 24 hours of uptime
- some players on my server have reported items such as lead and glass randomly disspearing from their inventory, although i have not experienced this issue. One players entire inventory was wiped randomly while he was swimming multiple times in different locations, rendering the game unplayable

**Comment by Agent77326** [comment]
#280

**Comment by Agent77326** [comment]
#442

**Comment by Measurity** [comment]
We're closing list-issues because they are hard to keep track of and continue to contain a lot of duplicates that are tracked elsewhere. Please only make 1 issue per bug so that we can track it more easily.
