### ISSUE TITLE
Bug after commit "Fixed one instance of items disappearing from the inventory."

### ISSUE THREAD

**Issue by fogrest** [SubnauticaNitrox/Nitrox#555]
After re-entering on the server, things in the inventory are duplicated. However, if one of the things is put into the chest on the rescue capsule, then the second things from the inventory disappear along with those that remained in the chest.
In addition, after re-entering on the server, the capsule needs to be repaired and a bug still remains when things in the chest on the capsule disappear.

**Comment by fogrest** [comment]
I think this is due to the fact that the user’s inventory is being returned in two different places. Once in the file EquipmentHelper.cs, and then in the file InventoryContainerHelper.cs 
In addition, another question arose as to why the logical expression "or" is used.

` if (equipmentplayer != null || owner.name == "Player")`

Возможно, стоит сделать проверку по идентификатору пользователя, который каждому задается при входе на сервер?

**Comment by cher123** [comment]
Look mother fu$&er, I know you, #556, #558, and a bunch of more have been messing with my gallery on my phone. I have the FBI looking into this because my mother works for them. I don't give up and that's why I'm on this page right now, I will find out who you are and I will do whatever it takes to make you stop doing what your doing, or if I have to, I will take further measures with the law. If there are any more cartoon pictures or empty files in my gallery or any more unity caches, I know where to go now and I know who to talk to. So, I suggest you fucking stop. I am not happy, and I will go through the tunnels of hell to put you in your place. You're fucking with the wrong one, I promise you ❣️❣️❣️❣️❣️❣️❤️❣️❤️

**Comment by cher123** [comment]
This is a warning, if I see any more on there, your ass is going down motherfucker!

**Comment by cher123** [comment]
d2r1980......

**Comment by cher123** [comment]
when the person you are asking questions to find out that you are hacking into someone else's account to do your dirty work, I hope the fuck they kick your dirty ass out of this GitHub, because you don't belong here and you don't belong on the face of this Earth

**Comment by NitroxPower** [comment]
@cher123 The FBI wont look to slove your iphone problem if you arent carefull... You shouldnt go in fake Sites download random stuff or idk what else you do with your phone i have been for 6 ages i havent been hacked not even once....be safe

**Comment by Measurity** [comment]
Closed due to inactivity. Open a new issue referencing this one and/or join our Nitrox Discord server.
