### ISSUE TITLE
Installer breaks after moving steam folder

### ISSUE THREAD

**Issue by chrsin** [SubnauticaNitrox/Nitrox#612]
I moved my subnautica folder to another drive (windows) and after that i couldn't use the installer.

I resolved by searching for Nitrox in regedit and deleted the installer entry for the nitrox installer

**Comment by alexanderheuts** [comment]
Nitrox is installed as any other program. If you move program files installers break. There's nothing that can be done about it.

**Comment by alexanderheuts** [comment]
The installer fails because you moved the files away. It is standard MSI behaviour to look for the installed files to decide what it can do. Steam doesn't care, it only moves the files themselves, but it does not update all the references of the Nitrox installer, which are broken by moving the files. You can fix it though.

Move the files back with steam. Run the installer and remove nitrox. Move the files of Subnautica and reinstall Nitrox after.
