### ISSUE TITLE
Play Multiplayer in VR?

### ISSUE THREAD

**Issue by Sichisky** [SubnauticaNitrox/Nitrox#743]
I tried to play multiplayer in VR,
if i press "connect to local(127.0.0.1)", it doesn't work.
what should i do?

**Comment by docquantum** [comment]
If you need help, go do the [Discord](https://discord.gg/E8B4X9s) (see the home page/ReadMe).

Did you follow the wiki and also start the server so that you have something to connect to?

[Link to the wiki](https://nitrox.fandom.com/wiki/Nitrox_Wiki), there are guides on getting the server running there:

**Comment by Sichisky** [comment]
When I tried just in PC version, it connected.
but, in VR version, it can't connect.
In VR, I can't choose color and nickname

**Comment by docquantum** [comment]
My best guess is that the VR version has a number of changes in both the menu and game files to accommodate VR features, which may be breaking the mod. I'm sure adding VR support and also SubZero support is planned, but getting it to work well on the normal version is a priority.

Like before, you can ask on Discord to see if anyone has gotten it to work in VR.

If you would like, feel free to change the title and description of this report to a feature request, requesting for VR support rather than writing it off as a bug.

**Comment by Measurity** [comment]
VR not supported right now. This is something to look into after beta.
