### ISSUE TITLE
Are the servers currently broken?

### ISSUE THREAD

**Issue by urlordjames** [SubnauticaNitrox/Nitrox#80]
I got everything setup properly however I'm not actually able to join any servers, it puts me into a game but I don't get a message in the server console and if I stop the console it doesn't kick me.  Am I doing anything wrong other than opening Nitrox\NitroxServer\bin\Debug\NitroxServer.exe?

**Comment by oliverslott** [comment]
Have you checked to see if there is any errors in the `output_log.txt` file?

**Comment by Measuring** [comment]
Believe that a recent update broke MP or some subsystems of it at least.  Console doesn't seem to do anything  for me, only the UI.

**Comment by urlordjames** [comment]
I think there are some errors, here is my log: https://gist.github.com/urlordjames/b6838bdf2a77cd96198a11a1dc30a586

**Comment by urlordjames** [comment]
The errors are refering to files in my C:\ which is unusual considering Subnautica is in my D:\, I might not have setup my DevVars.targets correctly.

**Comment by oliverslott** [comment]
If you look at line 518:
https://gist.github.com/urlordjames/b6838bdf2a77cd96198a11a1dc30a586#file-output_log-txt-L518
This is a known bug right now. @MarijnS95 have created a pull request with the fix: #78 
But a fast fix is finding the line: https://github.com/SubnauticaNitrox/Nitrox/blob/b9d505c88551520a52007ecaafdedffd340e18e3/NitroxPatcher/Patches/ConstructorInput_OnCraftingBegin_Patch.cs#L35
And place `OpCodes.Ldloc_2` as a argument instead of the `OpCodes.Ldloc_0`

**Comment by urlordjames** [comment]
Thanks a lot!
