### ISSUE TITLE
This mod will not work with QModManager.

### ISSUE THREAD

**Issue by joshuasuperboy** [SubnauticaNitrox/Nitrox#821]
When i try to load subnautica with QModManger installed it does not let me play. It says what you see below. I want to know if you can make it compatable with QModManger.
![Desktop Screenshot 2019 07 10 - 21 35 13 91](https://user-images.githubusercontent.com/32559193/61017984-cccecd80-a35a-11e9-85cc-e4f7b5f9d78c.png)

**Comment by JustinHoeky** [comment]
This message is there for a reason. QModManager and Nitrox are not compatible.
The Nitrox developers added this message since many people are asking about it or have issues
It's not know if it will be compatible, so you'll just have to wait untill it happens.

For now, uninstall QModManager like the message is telling you ^^

**Comment by HarveyBB** [comment]
They're incompatible for now
I hope they add support though bc nitrox + mods = Even more fun

**Comment by Coding-Hen** [comment]
Can we close this please as clearly doccumented as not compatible
