### ISSUE TITLE
Radio and fabricator in underwater base

### ISSUE THREAD

**Issue by paberthier15** [SubnauticaNitrox/Nitrox#838]
After each time the game has started, we have to deconstruct and construct these items because it's wrote they can't work. We cannot repair them. I don't know why this happen.

**Comment by flo-bzh** [comment]
Yeah we was so happy when we saw a awesome release of nitrox like this. We haven't try the mod since 1 year maybe. But the problem of fabricators are really anoying.. and it's not only about fabricator it's about every objects in the base. They are all in black skin like no power or underwater.
Unplayable but i hope those dev not gonna give up :D

**Comment by Coding-Hen** [comment]
Fixed with 79a3ec4c6b267c47735e1f7d2b4b36c4592efe8e

**Comment by Coding-Hen** [comment]
@Measurity This can be closed
