### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Pantking** [SubnauticaNitrox/Nitrox#91]
Hello

I would like to play with a friend in multiplayer 
but when I decided to install the mod that I did not understand how to install it. Can advise?

Sorry for my English 
Apologies for its audacity

**Comment by Staudey** [comment]
If you really don't understand the instructions you should probably wait
for a more accessible version of the mod, since you will probably run into
trouble during almost every part of the setup.

That is, of you don't understand how to use git, Visual Studio, and how to
work with code in general, you are going to have a hard time.

**Comment by Staudey** [comment]
Yes, this is exactly what I was talking about. You either need to learn how
to use the tools that are required, get a friend to help you out, or wait
for a version of the mod that has an easier installation process. Sorry,
but I doubt anyone here is willing to guide you through the whole process
in such detail.
I might work on a tutorial video or detailed guide in the future, but I
don't have the time right now.

**Comment by MarijnS95** [comment]
@Staudey Thanks for the offer, but please, don't make a youtube video.

The current level of skill required to compile and install the mod is completely intentional. The mod is in a very early stage, and still largely unstable. If someone is not able to understand the guide, I doubt they'll understand what the current state is, and why many things are not working.

Once this mod reaches the playable state, we **will** release the binaries with an easy to use installer, but until that point this source-code-only release is just for developers and modders willing to help out.

**Comment by Staudey** [comment]
Yeah, I understand. That would probably only lead to more confused issue
reports. Not that I would likely have found the time to do it in any case :D

**Comment by Sunrunner37** [comment]
This source code is only released for developers and not intended for consumption.  The mod is constantly in a broken, development state.  Wait for an official release.
