### ISSUE TITLE
Space For Modder Collaboration

### ISSUE THREAD

**Issue by MadMaxOfYore** [SubnauticaNitrox/Nitrox#99]
I was just wondering if there is a place that we, as contributors to the mod, can get support or suggestions from one another. Is that just the Discord channel at the moment? Or do we have something like a slack account anywhere where we can share design ideas without needing to open an issue on the github repo?

It would be nice to have a space for collaboration that wasn't constantly polluted by users asking questions while trying to get the mod running on their machines.

**Comment by MarijnS95** [comment]
Currently we have a couple private channels in the "Subnautica modding discord" where we can discuss without others intervening with overly-asked questions covered in the FAQ. That's the go-to place now, though I like the GitHub issue tracker and hope we can arrange some more moderation (since the maintainer lives in a different timezone).

**Comment by MadMaxOfYore** [comment]
Understood. Thanks!
